### PR TITLE
chore: biome as linter & formatter

### PR DESCRIPTION
**Pull request by huextrat**
# Add Biome for consistent code formatting and linting

## What does this PR do?
Adds Biome configuration to enforce consistent code style across the codebase. Biome is a fast, modern formatter and linter that will help maintain code quality and consistency across all developers.

## Key configurations:
- Enables automatic code formatting with 2-space indentation
- Configures JavaScript to use double quotes consistently
- Enables import organization
- Implements recommended linting rules with custom adjustments:
  - Allows non-null assertions
  - Permits array index keys
  - Warns on unused imports

## Why?
Having a standardized code formatting and linting setup ensures:
- Consistent code style across the entire codebase
- Reduced time spent on code reviews discussing formatting
- Automatic detection of potential issues and bugs
- Better developer experience with automated formatting

Adding this configuration early in the project lifecycle is crucial, as it:
- Prevents accumulation of inconsistent code styles
- Avoids large reformatting PRs later
- Sets coding standards from the start
- Makes it easier for new team members to adapt to the project's conventions

## Discussion Points
The current rule set is a starting point and can be adjusted based on team preferences. Feel free to discuss and suggest changes to:
- Formatting rules (indentation, line width, quote style)
- Linting rules severity levels
- Additional custom rules that could benefit the project
- Rules that might be too strict

### CODE REVIEW

**Comment by jmeistrich** [comment]
I think I've made a huge mistake... I'd wanted to take some time to think about this. I haven't used Biome before so I wanted to do some research into it, etc... 

But this codebase has been moving fast so now that it's been a couple days it's super conflicted 😅

I will get to it though! But at this point it may be easier to reset all of the changes to the formatted files and make this commit just the changes to add biome? And then after I merge it I'll immediately format everything - I think that'll be the easiest way to avoid conflicts?

**Comment by huextrat** [comment]
I've updated PR to only init Biome. Another PR is available https://github.com/LegendApp/legend-list/pull/21 with eslint & prettier by @sant3001 so pick what you prefer about linting tools

**Comment by jmeistrich** [comment]
I decided I'm excited to experiment with something new so let's do it!

**Comment by huextrat** [comment]
> I decided I'm excited to experiment with something new so let's do it!

Alright, I've been using Biole a lot this year on different projects, and I find it very fast for libraries and generally covers all the cases you need + it's easier to maintain than ESLint (flat config) and Prettier. The only downside is that it's not as widespread as ESLint and Prettier 🤷‍♂️

I'll be glad to hear from you once you've used it for a while 👍

**Pull request merged**
