### PR TITLE
feat: add reversed list feature

### PR DESCRIPTION
**Pull request by burhanyilmaz**

### CODE REVIEW

**Comment by jmeistrich** [comment]
Thank you!

Is the purpose of this to support a chat-like interface? I know other list libraries have a `reverse` property to support that, but I'd rather not do it this way because the transforms can cause some weird bugs.

So I'm planning to support that in a different way with a "firstItemAtBottom" prop or something, which would add padding to the top of the list for `scrollHeight - contentHeight`. And that padding would go to 0 when the content fills the ScrollView. Since we're absolutely positioning all of the containers anyway that should be a cleaner and more straightforward approach.

Would you like to do a PR to add that? 

Otherwise I'll leave this open so others could see it and use it as a temporary solution until we have that padding behavior. And I'll try to add that feature soon.

**Comment by burhanyilmaz** [comment]
@jmeistrich You are welcome!
First, I need to understand your solution method. After that, I can try to implement it.
We can leave this open until your solution is ready.

**Comment by jmeistrich** [comment]
Version 0.2.1 has a chat-like feature now. If you add these three props it should start at the bottom and keep scroll stuck to the bottom as long as you're within `autoScrollToBottomThreshold`.

`startAtBottom`: Adds padding to the top if content size is smaller than list size, to put the first item at the bottom
`autoScrollToBottom`: If you're scrolled to within `autoScrollToBottomThreshold` it will keep you scrolled to the bottom
`autoScrollToBottomThreshold`: Percent of screen height. Optional, defaults to 0.1

Can you try that out? And does that do what you want?

**Comment by burhanyilmaz** [comment]
Thank you for the solution @jmeistrich 🚀  🎊 

 I guess there are bugs. 
```
       <LegendList
                ref={scrollViewRef}
                style={[StyleSheet.absoluteFill, styles.scrollContainer]}
                contentContainerStyle={styles.listContainer}
                data={data}
                renderItem={renderItem}
                keyExtractor={(item) => item.id}
                estimatedItemLength={() => ESTIMATED_ITEM_LENGTH}
                drawDistance={1000}
                recycleItems={true}
                alignItemsAtEnd
                maintainScrollAtEnd
                maintainScrollAtEndThreshold={0.1}
                onEndReached={({ distanceFromEnd }) => {
                    console.log('onEndReached', distanceFromEnd);
                }}
                ListHeaderComponent={<View />}
                ListHeaderComponentStyle={styles.listHeader}
            />
```
It didn't work initially, but when I set maintainScrollAtEndThreshold to 150, it worked. Now, it scrolls to the end with animation. The fix is simple: `scrollToEnd({ ..., animated: maintainScrollAtEndAnimated ?? true })`. However, when I scroll to the top, it automatically scrolls back down.

https://github.com/user-attachments/assets/9f305ef2-6a10-4479-b8b7-e171c729a424

**Comment by jmeistrich** [comment]
150 would make the threshold 150 * screen height, so that would just always scroll to the end I think 😅. I'll test it some more tomorrow and see why it wasn't working.

**Comment by burhanyilmaz** [comment]
> 150 would make the threshold 150 * screen height, so that would just always scroll to the end I think 😅. I'll test it some more tomorrow and see why it wasn't working.

yes you are right :)
But when I set 100, it didn't work. after setting 150, it worked. 😄 

Thank you!

**Pull request closed without merging**
